# Generated by Django 6.0.4 on 2026-04-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0003_alter_monitor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='department',
            field=models.CharField(choices=[('physics', 'Monitores Fisica'), ('informatics_labs', 'Monitores Aulas de Software'), ('electrical', 'Monitores Laboratorios')], db_index=True, max_length=32),
        ),
    ]
